CONFIG_DEBUG=n
CONFIG_WERROR=n
CONFIG_OPTIMIZE=3

CONFIG_ARCH=x86_64
CONFIG_MACHINE=pc
CONFIG_TRIPLET=x86_64-pc-elf

CONFIG_UBSAN=n

CONFIG_INSTRUMENT=n

CONFIG_SERIAL_DEBUG_BAUD=38400
CONFIG_SERIAL_DEBUG_STOPBITS=1
CONFIG_SERIAL_DEBUG_WORDSZ=8
CONFIG_SERIAL_DEBUG_ENABLE=y

CONFIG_DEBUG_OBJECT_LIFE=n

CONFIG_PRINT_SYSCALLS=n
CONFIG_DEBUG_LOCKS=n

# set this to your toolchain path
TOOLCHAIN_PATH=/home/dbittman/code/r/twizzler/.tc
#/home/dbittman/code/twizzler/.tc

QEMU_FLAGS+="-enable-kvm"

